### ISSUE TITLE
I can't find the code that implements the frameless drag and drop and zoom in.

### ISSUE THREAD

**Issue by jiahengaa** [FlorianFe/Cells#1]
Your app is very cool！
I can't find the code that implements the frameless drag and drop and zoom in.
Can you point out？

**Comment by FlorianFe** [comment]
Hey and thanks =)

Zooming in and out is enabled by default. You can find the code for the frameless drag and drop in [_Cells/game-of-life/rough-window-frame/rough-window-frame.html_](https://github.com/FlorianFe/Cells/blob/master/game-of-life/rough-window-frame/rough-window-frame.html).

Here you can find the following CSS Code

```css
.drag-region
{
  /* ... */
  -webkit-app-region: drag;
}
```

which makes the window dragable on all elements with the class "drag-region" in the Shadow DOM of **&lt;rough-window-frame&gt;**. You can find it in Electrons [documentation of Frameless Window](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region). 

I hope I was able to help you =)

**Comment by jiahengaa** [comment]
Your parsing is very clear, thank you very much!  Now I figuring out how to use -webkit-app-region and -webkit-user-select.
